version: "2"

networks:
  app-network:
    driver: bridge

services:
  library:
    image: library
    ports:
      - 8888:8888
    build:
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - library-mysql
    deploy:
      replicas: 4
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10
  library-mysql:
    image: mysql:latest
    container_name: library-mysql
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql/data
    ports:
      - 3306:3306
    env_file: ./files/env/.env
    networks:
      - app-network
    environment:
      - MYSQL_PASSWORD=${POSTGRES_PASSWORD}
      - MYSQL_USER=${POSTGRES_USER}
      - MYSQL_DB=${POSTGRES_DB}
  library-migration:
    image: library-migration
    networks:
      - app-network
    depends_on:
      - library-mysql
    build:
      dockerfile: migration.dockerfile
    profiles:
      - donotstart
  library-seeder:
    image: library-seeder
    networks:
      - app-network
    depends_on:
      - library-mysql
    build:
      dockerfile: seeder.dockerfile
    profiles:
      - donotstart
#  neo-post-nginx:
#    image: neo-post-nginx
#    networks:
#      - app-network
#    build:
#      dockerfile: nginx.dockerfile

volumes:
  mysql-data: