name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22' ]

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        with:
          go-version: '1.22.x'
        run: |
          go get .
          go mod tidy
